# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('access_token', models.CharField(help_text='Used to authenticate as the user on Reddit', max_length=255)),
                ('refresh_token', models.CharField(help_text='Used to refresh the access_token', max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, help_text='The identifier for this task. Shown publicly.', primary_key=True, serialize=False)),
                ('comments_deleted', models.PositiveSmallIntegerField(default=0)),
                ('submissions_deleted', models.PositiveSmallIntegerField(default=0)),
                ('state', models.PositiveSmallIntegerField(choices=[(10, 'Asked user to authorize'), (20, 'Received code and state'), (30, 'Authenticated as user on Reddit'), (40, 'Deleting content'), (50, 'Finished'), (100, 'Unknown error'), (101, 'Access denied')], default=10, help_text='How far are we along in the process.')),
            ],
        ),
    ]
