# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170910_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
