# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170929_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Asked user to authorize'), (20, 'Authenticated as user on Reddit'), (30, 'Received code and state'), (40, 'Deleting comments'), (41, 'Deleting submissions'), (50, 'Finished'), (100, 'Unknown error'), (101, 'Access denied')], default=10, help_text='How far are we along in the process.'),
        ),
    ]
